baseURL = ""
title = "TailBliss"
languageCode = "en-us"
DefaultContentLanguage = "en"
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[pagination]
  pagerSize = 6

darkmode_js = ["assets/js/darkmode.js"]

enableInlineShortcodes = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = "https"
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.typographer]
        apostrophe = "&rsquo;"
        disable = false
        ellipsis = "&hellip;"
        emDash = "&mdash;"
        enDash = "&ndash;"
        leftAngleQuote = "&laquo;"
        leftDoubleQuote = "&ldquo;"
        leftSingleQuote = "&lsquo;"
        rightAngleQuote = "&raquo;"
        rightDoubleQuote = "&rdquo;"
        rightSingleQuote = "&rsquo;"
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false
        title = true
      autoHeadingID = true
      autoHeadingIDType = "github"
      wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[params]
  author = "Nusser Studios"
  authorimage = "../assets/images/global/author.webp"
  og_image = "/images/tailbliss-cover.png"
  moto = "Super Fast, and Flexible"
  description = "A Hugo theme built with love, using TailwindCSS 3, Alpine.JS, and Hugo Pipes. Images are optimized for use with Hugo Pipes for WebP format."
  disable_theme_toggle = false
  disable_stay_uptodate = false

  [params.p1]
    heading = "Our mission"
    image = "images/pages/our-mission.png"
    [[params.p1.content]]
      text = "Sagittis scelerisque nulla cursus in enim consectetur quam..."
    [[params.p1.content]]
      text = "Sollicitudin tristique eros erat odio sed vitae..."
    [[params.p1.content]]
      text = "Rhoncus nisl, libero egestas diam fermentum dui..."

  [params.p2]
    heading = "Just in time for Hacktoberfest with JIT Tailwind."
    image = "images/pages/hacktoberfest.jpg"
    [[params.p2.content]]
      text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit..."

  [params.p3]
    heading = "Backed by world-renowned investors"
    [[params.p3.content]]
      text = "Sagittis scelerisque nulla cursus in enim consectetur quam..."
    [[params.p3.links]]
      text = "Meet our investors and advisors"
      url = "#"
    [[params.p3.logos]]
      identifier = "a"
      image = "images/global/sample-logo.svg"
      alt = "a"

  [params.p4]
    heading = "From the blog"
    [[params.p4.content]]
      text = "Lorem ipsum dolor sit amet consectetur, adipisicing elit."

  [params.p5]
    heading = "Stay Up to Date"
    [[params.p5.content]]
      text = "Sagittis scelerisque nulla cursus in enim consectetur quam..."
    action = "#"
    label = "Email address"
    placeholder = "Enter your email"
    button = "Notify me"

[menu]
  [[menu.main]]
    identifier = "prose"
    name = "Prose"
    url = "/prose/"
    weight = 10
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

[taxonomies]
  category = "Categories"
  tag = "Tags"

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.114.0"
