baseURL = 'https://latticecorp.cloud/'
theme = "hugo-brewm"
languageCode = 'en-us'
ignoreFiles = [ '\.redacted', '\.old','\.bak', '\.tmp', '\.swp', '\.DS_Store']

[markup]

    ## Table of contents settings
    [markup.tableOfContents]
        ## Minimum heading level to include
        startLevel = 2
        ## Maximum heading level to include
        endLevel = 3
        ## Use ordered list for TOC
        ordered = false

    ## Code highlighting settings
    [markup.highlight]
        ## Enable code fence highlighting
        codeFences = true
        ## Lines to highlight
        hl_Lines = ""
        ## Starting line number
        lineNoStart = 1
        ## Show line numbers
        lineNos = false
        ## Put line numbers in table
        lineNumbersInTable = true
        ## Use classes for styling
        noClasses = false
        ## Width of tab character
        tabWidth = 4

    ## Goldmark markdown processor settings
    [markup.goldmark]
        [markup.goldmark.renderer]
            ## Allow HTML in markdown
            unsafe = true


[params]
    title = 'Lattice Services'
    description = "Somos una consultora tecnológica, especializada en ingeniería de datos, MLOps, DataOps y Genia. Nuestra misión es transformar y potenciar equipos existentes, llevándolos al siguiente nivel de alto rendimiento. Fusionamos innovación y experiencia para optimizar procesos, acelerar la toma de decisiones basada en datos y crear soluciones personalizadas que impulsen el crecimiento y la competitividad de tu negocio."
    copyright = "Copyright 2025 (c) Lattice Corp"
    extMeta = true
    coffeeStat = true

    [params.author]
    name = "Lattice Corp"
    email = "email@example.com"
    coauthor = [
      { name = "mnava", bio = "" },
      { name = "jcort", bio = "" },
      { name = "agonz", bio = "" }
    ]

    ## Comments configuration
    [params.comments]
        disabled = true

    [params.feed]
        flowlines = true
        flowlinesLimit = 21

    [params.home]
        disableSlide = false
        disableListing = true

    [params.search]
        enable = false
        pagefind = true